In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter('ignore', UserWarning)

In [2]:
rental = pd.read_csv('Affordable_Rental_Housing_Developments.csv', encoding = 'gbk', header = 0)
rental.columns = rental.columns.str.upper()
rental.head()

,COMMUNITY AREA NAME,COMMUNITY AREA NUMBER,PROPERTY TYPE,PROPERTY NAME,ADDRESS,ZIP CODE,PHONE NUMBER,MANAGEMENT COMPANY,UNITS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,Douglas,35,ARO,Lake Park LLC,243 E. 31st St.,60616,773-466-8332,D Properties,1,NaN,NaN,NaN,NaN,NaN
1,Logan Square,22,Multifamily,Tierra Linda Apts.,1802 N. Sawyer Ave.,60647,773-276-5338,LUCHA,3,NaN,NaN,NaN,NaN,NaN
2,Near North Side,8,ARO,Onni Atrium Devp.,202 W. Hill St.,60610,312-585-6776,Onni Group,43,NaN,NaN,NaN,NaN,NaN
3,Near West Side,28,ARO,The Duncan,1515 W. Monroe St.,60607,217-779-5697,FLATS Leasing,52,NaN,NaN,NaN,NaN,NaN
4,West Englewood,67,Multifamily,New West Englewood Homes,2109 W. 63rd St.,60636,773-434-4929,Interfaith Housing Corp.,12,NaN,NaN,NaN,NaN,NaN

In [3]:
rental.drop(['X COORDINATE', 'Y COORDINATE'], axis = 1, inplace = True)
rental.head(10)

,COMMUNITY AREA NAME,COMMUNITY AREA NUMBER,PROPERTY TYPE,PROPERTY NAME,ADDRESS,ZIP CODE,PHONE NUMBER,MANAGEMENT COMPANY,UNITS,LATITUDE,LONGITUDE,LOCATION
0,Douglas,35,ARO,Lake Park LLC,243 E. 31st St.,60616,773-466-8332,D Properties,1,NaN,NaN,NaN
1,Logan Square,22,Multifamily,Tierra Linda Apts.,1802 N. Sawyer Ave.,60647,773-276-5338,LUCHA,3,NaN,NaN,NaN
2,Near North Side,8,ARO,Onni Atrium Devp.,202 W. Hill St.,60610,312-585-6776,Onni Group,43,NaN,NaN,NaN
3,Near West Side,28,ARO,The Duncan,1515 W. Monroe St.,60607,217-779-5697,FLATS Leasing,52,NaN,NaN,NaN
4,West Englewood,67,Multifamily,New West Englewood Homes,2109 W. 63rd St.,60636,773-434-4929,Interfaith Housing Corp.,12,NaN,NaN,NaN
5,Englewood,68,Multifamily,Antioch Homes II,301 W. Marquette Road,60621,773-994-4546,"Universal Management Service, Inc.",69,41.772564,-87.632419,"(41.7725637689, -87.6324193182)"
6,Uptown,3,Senior,Ruth Shriman House,4040 N. Sheridan Road,60613,773-665-2210,Interfaith Housing Corp.,231,41.955685,-87.654725,"(41.9556850173, -87.6547251281)"
7,Humboldt Park,23,Multifamily,Tierra Linda Apts.,1649-51 N. Drake Ave.,60647,773-276-5338,LUCHA,6,NaN,NaN,NaN
8,Grand Boulevard,38,Multifamily,Legends South - Hansberry Square,4034 S. State St.,60609,773-548-8800,Interstate Realty Management Co.,181,41.820911,-87.626526,"(41.8209108342, -87.6265256539)"
9,South Lawndale,30,Multifamily,Casa Sor Juana,2700 S. Drake Ave.,60623,312-850-1935,The Resurrection Project,29,41.842477,-87.713667,"(41.842476558, -87.713667149)"

In [4]:
rental.to_csv('Affordable_Rental_Housing_Developments_cleaned.csv', encoding='utf-8', index=False)